---
grails:
    profile: rest-api
    codegen:
        defaultPackage: cmmv.backend
    cors:
        enabled: true
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
jasypt:
    algorithm: "PBEWITHSHA256AND128BITAES-CBC-BC"
    providerName: "BC"
    password: "s3kr1t"
    keyObtentionIterations: 1000

management:
    endpoints:
        enabled-by-default: false

server:
    port:
        8882
cache:
    headers:
        presets:
            unauthed_page:
                shared: true
                validFor: 300 # 5 minute refresh window
            authed_page: false # No caching for logged in user
            content:
                shared: true
                validFor: 3600 # 1hr on content
            recent_items_feed:
                shared: true
                validFor: 1800 # 30 minute throttle on RSS updates
            search_results:
                validFor: 60
                shared: true
            taxonomy_results:
                validFor: 60
                shared: true
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 10000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 10485760000
            maxRequestSize: 10485760000
    converters:
        encoding: UTF-8

---
grails:
    cors:
        enabled: true
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:2345/cmmv
    test:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://db:5432/cmmv
    production:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://db:5432/cmmv
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED


twilio :
     host: https://api.twilio.com
     apiID: ACb782cd08cd384f29538e90d6a88d8939
     apiPass: b7a856b44c9af30cc95837943ab0d47c
     smsUrl : '/2010-04-01/Accounts/ACb782cd08cd384f29538e90d6a88d8939/Messages.json'
     number : "+12055486394"
